### ISSUE TITLE
Doesn't boot

### ISSUE THREAD

**Issue by MirkoCovizzi** [davinci-dev/android_kernel_xiaomi_davinci#1]
It seems this kernel doesn't work. It gets stuck in bootloop.

**Comment by PIPIPIG233666** [comment]
gib log plz

**Comment by PIPIPIG233666** [comment]
I havnt got the phone so this kernel is untested.
Anyway my phone is gonna arrive soon.
Will check later.

**Comment by MirkoCovizzi** [comment]
Is a dmesg log fine?

**Comment by PIPIPIG233666** [comment]
yup

**Comment by MirkoCovizzi** [comment]
I've collected this, but so far it seems it registers fine up to first stage, then it registers recovery, which is the only other place where I can backup the log.
Also, I compared it with stock boot log, and it's 99.9% equal, up to first stage, then stock completes first stage and second stage, and boot, while the compiled kernel goes into recovery.

https://pastebin.com/1fwfWjBC

**Comment by MirkoCovizzi** [comment]
This is the stock log, after first stage init:

https://pastebin.com/R47A0Pkx
