### ISSUE TITLE
Unable to build LineageOS 16.0

### ISSUE THREAD

**Issue by 0x24D** [davinci-dev/android_kernel_xiaomi_davinci#3]
Hello, over the past two days I have been trying to build LineageOS 16.0 for my Davinci using https://wiki.lineageos.org/devices/tissot/build as reference. Unfortunately the build fails part way through the brunch process. Please find full output [here](https://gist.github.com/0x24D/f0471326897ad0881c4da136a4ea8896)

My full process:
1. Follow linked LineageOS guide from _Build LineageOS and LineageOS Recovery_ to _Download the source code_
2. Clone https://github.com/davinci-dev/android_device_xiaomi_davinci (lineage-16.0 branch) to `device/xiaomi/davinci`
3. Clone https://github.com/davinci-dev/android_device_xiaomi_sm6150-common (lineage-16.0 branch) to `device/xiaomi/sm6150-common`
4. Clone https://github.com/davinci-dev/android_kernel_xiaomi_davinci (lineage-16.0 branch) to `kernel/xiaomi/davinci`
5. Clone https://github.com/davinci-dev/vendor_xiaomi (lineage-16.0 branch) to `vendor/xiaomi`
6. Continue LineageOS guide from _Turn on caching to speed up build_

Apologies if this is a simple error to resolve, this is my first time building for Android.

**Comment by PIPIPIG233666** [comment]
16 is Deprecated, will publish 17 source ASAP.
